language: java
cache:
  directories:
    - $HOME/.m2

services:
  - xvfb

before_install:
  - sudo apt-get install jq
  - wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r .assets[0].browser_download_url)

after_success:
  - mvn clean verify jacoco:report coveralls:report
  - ls target/site/
  - ls inventarios-service/target/
  - ls inventarios-desktop-testing-api/target/
  - java -jar ~/codacy-coverage-reporter-assembly-latest.jar report -l Java -r inventarios-service/target/site/jacoco/jacoco.xml --partial
  - java -jar ~/codacy-coverage-reporter-assembly-latest.jar report -l Java -r inventarios-desktop-testing-api/target/site/jacoco/jacoco.xml final

jdk:
  - openjdk12
