# enviroment settings
environment:
  matrix:
  - JAVA_HOME: C:\Program Files\Java\jdk12

# install required tools (maven, secure-file, encrypted files)
install:
  - cmd: echo %JAVA_HOME%
  - cmd: echo %M2_HOME%
  - cmd: java -version

build_script:
  - mvn clean install -DskipTests -B

 # verify artifacts
test_script:
  - mvn verify -B
  
after_test:
  - ps: Start-FileDownload 'https://ci.appveyor.com/api/buildjobs/t8yfa0v7jnhuo2b6/artifacts/jq.exe'
  - ps: Start-FileDownload 'https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest' | jq -r .assets[0].browser_download_url
  - ps: java -jar codacy-coverage-reporter-assembly.jar report -l Java -r jacoco.xml
  - dir

cache:
  - C:\Users\appveyor\.m2