# enviroment settings
environment:
  matrix:
  - JAVA_HOME: C:\Program Files\Java\jdk12

# install required tools (maven, secure-file, encrypted files)
install:
  - cmd: echo %JAVA_HOME%
  - cmd: echo %M2_HOME%
  - cmd: java -version

build_script:
  - mvn clean install -DskipTests -B

 # verify artifacts
test_script:
  - mvn verify jacoco:report -B
  
after_test:
  # - ps: Start-FileDownload 'https://ci.appveyor.com/api/buildjobs/t8yfa0v7jnhuo2b6/artifacts/jq.exe'
  - ps: Start-FileDownload 'https://github.com/codacy/codacy-coverage-reporter/releases/download/6.0.2/codacy-coverage-reporter-6.0.2-assembly.jar'
  - dir
  - cd inventarios-service/target
  - dir
  - cd ..
  - ps: java -jar codacy-coverage-reporter-6.0.2-assembly.jar report -l Java -r inventarios-service/target/site/jacoco/jacoco.xml --partial
  - ps: java -jar codacy-coverage-reporter-6.0.2-assembly.jar report -l Java -r inventarios-desktop-testing-api/target/site/jacoco/jacoco.xml final

cache:
  - C:\Users\appveyor\.m2