# enviroment settings
environment:
  matrix:
  - JAVA_HOME: C:\Program Files\Java\jdk12

# install required tools (maven, secure-file, encrypted files)
install:
  - cmd: echo %JAVA_HOME%
  - cmd: echo %M2_HOME%

build_script:
  - mvn clean install -DskipTests -B

 # verify artifacts
test_script:
  - mvn verify -B
  
after_test:
  - curl -Ls -o codacy-coverage-reporter-assembly.jar $(curl -Ls https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r '.assets | map({content_type, browser_download_url} | select(.content_type | contains("java-archive"))) | .[0].browser_download_url')
  - java -jar codacy-coverage-reporter-assembly.jar report -l Java -r jacoco.xml

cache:
  - C:\Users\appveyor\.m2