/* 
 * Copyright (C) 2019 Ruslan López Carro
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package inventarios.desktop;

import inventarios.desktop.navigation.NavigationHandler;
import inventarios.service.EmployeeService;
import inventarios.to.EmployeeDetail;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.stereotype.Component;

import javax.swing.BorderFactory;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Font;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ResourceBundle;

/**
 *
 * @author IDELFONSO
 */
@Component
public class EmployeeRegistration extends JFrame {
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JTextField txtAddress;
    private JTextField txtArrivingTime;
    private JTextField txtFirstLastName;
    private JTextField txtId;
    private JTextField txtLastLastName;
    private JTextField txtLeavingTime;
    private JTextField txtName;
    private JTextField txtPosition;
    // End of variables declaration//GEN-END:variables

    @Autowired
    @Qualifier("employeeVisitor")
    private NavigationHandler navigationHandler;

    @Autowired
    private EmployeeService employeeService;

    /**
     * Creates new form Empleados
     */
    public EmployeeRegistration() {
        initComponents();
        ((JPanel) getContentPane()).setOpaque(false);
        ImageIcon uno;
        uno = new ImageIcon(this.getClass().getResource("/ImgFondos/abstract.jpg"));
        JLabel fondo = new JLabel();
        fondo.setIcon(uno);
        getLayeredPane().add(fondo, JLayeredPane.FRAME_CONTENT_LAYER);
        fondo.setBounds(0, 0, uno.getIconWidth(), uno.getIconHeight());
    }
    
    private void clearFields() {
        txtId.setText(null);
        txtName.setText(null);
        txtFirstLastName.setText(null);
        txtLastLastName.setText(null);
        txtAddress.setText(null);
        txtPosition.setText(null);
        txtArrivingTime.setText(null);
        txtLeavingTime.setText(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        GridBagConstraints gridBagConstraints;

        JPanel pnlTitle = new JPanel();
        JLabel windowTitle = new JLabel();
        JPanel pnlContents = new JPanel();
        txtId = new JTextField();
        JLabel lblId = new JLabel();
        JLabel lblFirstName = new JLabel();
        txtName = new JTextField();
        JLabel lblFirstLastName = new JLabel();
        txtFirstLastName = new JTextField();
        JLabel lblLastLastName = new JLabel();
        txtLastLastName = new JTextField();
        JLabel lblAdress = new JLabel();
        txtAddress = new JTextField();
        JLabel lblPosition = new JLabel();
        txtPosition = new JTextField();
        JLabel lblArrivingTime = new JLabel();
        txtArrivingTime = new JTextField();
        JLabel lblLeavingTime = new JLabel();
        txtLeavingTime = new JTextField();
        JPanel pnlButtons = new JPanel();
        JButton btnSave = new JButton();
        JButton jButton2 = new JButton();
        JButton btnMenu = new JButton();
        JButton btnClose = new JButton();

        setTitle("null");

        pnlTitle.setLayout(new GridBagLayout());

        windowTitle.setFont(new Font("Arial Black", 1, 18)); // NOI18N
        ResourceBundle bundle = ResourceBundle.getBundle("inventarios/gui/desktop/Bundle"); // NOI18N
        windowTitle.setText(bundle.getString("EmployeeRegistration.windowTitle.text")); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.fill = GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = GridBagConstraints.BASELINE;
        pnlTitle.add(windowTitle, gridBagConstraints);

        getContentPane().add(pnlTitle, BorderLayout.NORTH);

        pnlContents.setLayout(new GridBagLayout());
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 205;
        gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new Insets(15, 12, 0, 0);
        pnlContents.add(txtId, gridBagConstraints);

        lblId.setFont(new Font("Tahoma", 1, 18)); // NOI18N
        lblId.setText(bundle.getString("EmployeeRegistration.lblId.text")); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new Insets(11, 10, 0, 0);
        pnlContents.add(lblId, gridBagConstraints);

        lblFirstName.setFont(new Font("Tahoma", 1, 18)); // NOI18N
        lblFirstName.setText(bundle.getString("EmployeeRegistration.lblFirstName.text")); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new Insets(44, 10, 0, 0);
        pnlContents.add(lblFirstName, gridBagConstraints);
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 205;
        gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new Insets(28, 12, 0, 0);
        pnlContents.add(txtName, gridBagConstraints);

        lblFirstLastName.setFont(new Font("Tahoma", 1, 18)); // NOI18N
        lblFirstLastName.setText(bundle.getString("EmployeeRegistration.lblFirstLastName.text")); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new Insets(61, 10, 0, 0);
        pnlContents.add(lblFirstLastName, gridBagConstraints);
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 205;
        gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new Insets(54, 12, 0, 0);
        pnlContents.add(txtFirstLastName, gridBagConstraints);

        lblLastLastName.setFont(new Font("Tahoma", 1, 18)); // NOI18N
        lblLastLastName.setText(bundle.getString("EmployeeRegistration.lblLastLastName.text")); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new Insets(48, 10, 0, 0);
        pnlContents.add(lblLastLastName, gridBagConstraints);
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 205;
        gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new Insets(48, 10, 0, 0);
        pnlContents.add(txtLastLastName, gridBagConstraints);

        lblAdress.setFont(new Font("Tahoma", 1, 18)); // NOI18N
        lblAdress.setText(bundle.getString("EmployeeRegistration.lblAdress.text")); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new Insets(47, 10, 0, 0);
        pnlContents.add(lblAdress, gridBagConstraints);
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 205;
        gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new Insets(51, 10, 0, 0);
        pnlContents.add(txtAddress, gridBagConstraints);

        lblPosition.setFont(new Font("Tahoma", 1, 18)); // NOI18N
        lblPosition.setText(bundle.getString("EmployeeRegistration.lblPosition.text")); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new Insets(39, 10, 0, 0);
        pnlContents.add(lblPosition, gridBagConstraints);
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 205;
        gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new Insets(43, 10, 0, 0);
        pnlContents.add(txtPosition, gridBagConstraints);

        lblArrivingTime.setText(bundle.getString("EmployeeRegistration.lblArrivingTime.text")); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipadx = 13;
        gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new Insets(21, 10, 0, 0);
        pnlContents.add(lblArrivingTime, gridBagConstraints);
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 205;
        gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new Insets(18, 10, 65, 0);
        pnlContents.add(txtArrivingTime, gridBagConstraints);

        lblLeavingTime.setText(bundle.getString("EmployeeRegistration.lblLeavingTime.text")); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.ipadx = 21;
        gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new Insets(21, 8, 0, 0);
        pnlContents.add(lblLeavingTime, gridBagConstraints);
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 79;
        gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new Insets(18, 4, 65, 55);
        pnlContents.add(txtLeavingTime, gridBagConstraints);

        getContentPane().add(pnlContents, BorderLayout.CENTER);

        btnSave.setFont(new Font("Verdana", 1, 18)); // NOI18N
        btnSave.setText(bundle.getString("EmployeeRegistration.btnSave.text")); // NOI18N
        btnSave.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jButton2.setFont(new Font("Verdana", 1, 18)); // NOI18N
        jButton2.setText(bundle.getString("EmployeeRegistration.jButton2.text")); // NOI18N
        jButton2.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnMenu.setBackground(new Color(255, 255, 255));
        btnMenu.setFont(new Font("Tahoma", 1, 24)); // NOI18N
        btnMenu.setText(bundle.getString("EmployeeRegistration.btnMenu.text")); // NOI18N
        btnMenu.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));
        btnMenu.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });

        btnClose.setText(bundle.getString("EmployeeRegistration.btnClose.text")); // NOI18N
        btnClose.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        GroupLayout pnlButtonsLayout = new GroupLayout(pnlButtons);
        pnlButtons.setLayout(pnlButtonsLayout);
        pnlButtonsLayout.setHorizontalGroup(pnlButtonsLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(pnlButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSave)
                .addGap(74, 74, 74)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(btnMenu, GroupLayout.PREFERRED_SIZE, 104, GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addComponent(btnClose)
                .addContainerGap(49, Short.MAX_VALUE))
        );
        pnlButtonsLayout.setVerticalGroup(pnlButtonsLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(pnlButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlButtonsLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(jButton2)
                    .addComponent(btnMenu)
                    .addComponent(btnClose))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(pnlButtons, BorderLayout.SOUTH);

        setBounds(0, 0, 649, 611);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        String registrationNumber = txtId.getText();
        String name = txtName.getText();
        String lastName1 = txtFirstLastName.getText();
        String lastName2 = txtLastLastName.getText();
        String domicilios = txtAddress.getText();
        String position = txtPosition.getText();
        String timeIn = txtArrivingTime.getText();
        String timeOut = txtLeavingTime.getText();

        EmployeeDetail b = new EmployeeDetail(null, registrationNumber, name, lastName1, lastName2, domicilios, position, timeIn, timeOut);

        employeeService.save(b);

        JOptionPane.showMessageDialog(null, "se han guardado los datos");
        clearFields();


    }//GEN-LAST:event_btnSaveActionPerformed

    private void jButton2ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        navigationHandler.goToFrame(this, ListaEmpleados.class);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnMenuActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        navigationHandler.goToMenu(this);
    }//GEN-LAST:event_btnMenuActionPerformed

    private void btnCloseActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        navigationHandler.goToMenu(this);
    }//GEN-LAST:event_btnCloseActionPerformed
   
}
