/* 
 * Copyright (C) 2019 Ruslan LÃ³pez Carro
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package inventarios.desktop;

import inventarios.desktop.navigation.NavigationHandler;
import inventarios.service.EmployeeService;
import inventarios.to.EmployeeDetail;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.stereotype.Component;

import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.LayoutStyle;
import javax.swing.table.DefaultTableModel;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import java.util.ResourceBundle;

/**
 *
 * @author IDELFONSO
 */
@Component
public class ListaEmpleados extends JFrame {

    // Variables declaration - do not modify//GEN-BEGIN:variables
    JTable tblEmployees;
    // End of variables declaration//GEN-END:variables

    @Autowired
    private EmployeeService employeeService;

    @Autowired
    @Qualifier("listaEmpleadosVisitor")
    NavigationHandler navigationHandler;

    private DefaultTableModel modelo;
    private int cont = 0;

    /**
     * Creates new form TablaClientes
     */
    public ListaEmpleados() {
        initComponents();
        ((JPanel) getContentPane()).setOpaque(false);
        ImageIcon uno;
        uno = new ImageIcon(this.getClass().getResource("/ImgFondos/tabla.jpg"));
        JLabel fondo = new JLabel();
        fondo.setIcon(uno);
        getLayeredPane().add(fondo, JLayeredPane.FRAME_CONTENT_LAYER);
        fondo.setBounds(0, 0, uno.getIconWidth(), uno.getIconHeight());
    }

    public void cargarinterfaz() {
        String x[][] = {};
        String columnas[] = {"matricula", "nombre", "primera apellido", "segundo apellido", "domicilio", "puesto", "Hora de entrada", "Hora de salida"};
        modelo = new DefaultTableModel(x, columnas);
        tblEmployees.setModel(modelo);
    }

    public void mostrardatos(EmployeeDetail c) {

        modelo.insertRow(cont, new Object[]{});

        modelo.setValueAt(c.getNumber(), cont, 0);
        modelo.setValueAt(c.getName(), cont, 1);
        modelo.setValueAt(c.getMiddleName(), cont, 2);
        modelo.setValueAt(c.getLastName(), cont, 3);
        modelo.setValueAt(c.getHomeAdress(), cont, 4);
        modelo.setValueAt(c.getPosition(), cont, 5);
        modelo.setValueAt(c.getStartTime(), cont, 6);
        modelo.setValueAt(c.getEndTime(), cont, 7);

        cont++;

    }

    @Override
    public void setVisible(boolean b) {
        super.setVisible(b);
        cargarinterfaz();
        EmployeeDetail c;
        cont = 0;

        List<EmployeeDetail> employeeDetails = employeeService.findAll();
        for (int i = 0; i < employeeDetails.size(); i++) {
            c = (EmployeeDetail) employeeDetails.get(i);
            mostrardatos(c);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLabel lblTitle = new JLabel();
        JScrollPane scrlEmployees = new JScrollPane();
        tblEmployees = new JTable();
        JButton btnGetBack = new JButton();
        JButton btnClose = new JButton();

        lblTitle.setFont(new Font("Verdana", 1, 18)); // NOI18N
        ResourceBundle bundle = ResourceBundle.getBundle("inventarios/gui/desktop/Bundle"); // NOI18N
        lblTitle.setText(bundle.getString("ListaEmpleados.lblTitle.text")); // NOI18N

        scrlEmployees.setViewportView(tblEmployees);

        btnGetBack.setFont(new Font("Verdana", 1, 18)); // NOI18N
        btnGetBack.setText(bundle.getString("ListaEmpleados.btnGetBack.text")); // NOI18N
        btnGetBack.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btnGetBackActionPerformed(evt);
            }
        });

        btnClose.setText(bundle.getString("ListaEmpleados.btnClose.text")); // NOI18N
        btnClose.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(scrlEmployees, GroupLayout.PREFERRED_SIZE, 668, GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitle, GroupLayout.PREFERRED_SIZE, 334, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnGetBack)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClose)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitle, GroupLayout.PREFERRED_SIZE, 34, GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGetBack)
                    .addComponent(btnClose))
                .addGap(18, 18, 18)
                .addComponent(scrlEmployees, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGetBackActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnGetBackActionPerformed
        navigationHandler.goToEmployeeRegistration(this);
    }//GEN-LAST:event_btnGetBackActionPerformed

    private void btnCloseActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        navigationHandler.goToEmployeeRegistration(this);
    }//GEN-LAST:event_btnCloseActionPerformed

}
