/* 
 * Copyright (C) 2019 Ruslan LÃ³pez Carro
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package inventarios.desktop;

import inventarios.service.EmployeeService;
import inventarios.to.EmployeeDetail;
import java.util.List;
import org.springframework.stereotype.Component;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import org.springframework.beans.factory.annotation.Autowired;

/**
 *
 * @author IDELFONSO
 */
@Component
public class ListaEmpleados extends javax.swing.JFrame {
    
    @Autowired
    EmployeeService employeeService;

    private DefaultTableModel modelo;
    int cont = 0;

    /**
     * Creates new form TablaClientes
     */
    public ListaEmpleados() {
        initComponents();
        ((JPanel) getContentPane()).setOpaque(false);
        ImageIcon uno;
        uno = new ImageIcon(this.getClass().getResource("/ImgFondos/tabla.jpg"));
        JLabel fondo = new JLabel();
        fondo.setIcon(uno);
        getLayeredPane().add(fondo, JLayeredPane.FRAME_CONTENT_LAYER);
        fondo.setBounds(0, 0, uno.getIconWidth(), uno.getIconHeight());
    }

    public void cargarinterfaz() {
        String x[][] = {};
        String columnas[] = {"matricula", "nombre", "primera apellido", "segundo apellido", "domicilio", "puesto", "Hora de entrada", "Hora de salida"};
        modelo = new DefaultTableModel(x, columnas);
        tblEmployees.setModel(modelo);
    }

    public void mostrardatos(EmployeeDetail c) {

        modelo.insertRow(cont, new Object[]{});

        modelo.setValueAt(c.getNumber(), cont, 0);
        modelo.setValueAt(c.getName(), cont, 1);
        modelo.setValueAt(c.getMiddleName(), cont, 2);
        modelo.setValueAt(c.getLastName(), cont, 3);
        modelo.setValueAt(c.getHomeAdress(), cont, 4);
        modelo.setValueAt(c.getPosition(), cont, 5);
        modelo.setValueAt(c.getStartTime(), cont, 6);
        modelo.setValueAt(c.getEndTime(), cont, 7);

        cont++;

    }

    @Override
    public void setVisible(boolean b) {
        super.setVisible(b);
        cargarinterfaz();
        EmployeeDetail c;

        List<EmployeeDetail> employeeDetails = employeeService.findAll();
        for (int i = 0; i < employeeDetails.size(); i++) {
            c = (EmployeeDetail) employeeDetails.get(i);
            mostrardatos(c);
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        scrlEmployees = new javax.swing.JScrollPane();
        tblEmployees = new javax.swing.JTable();
        btnGetBack = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();

        lblTitle.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("inventarios/gui/desktop/Bundle"); // NOI18N
        lblTitle.setText(bundle.getString("ListaEmpleados.lblTitle.text")); // NOI18N

        tblEmployees.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrlEmployees.setViewportView(tblEmployees);

        btnGetBack.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnGetBack.setText(bundle.getString("ListaEmpleados.btnGetBack.text")); // NOI18N
        btnGetBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetBackActionPerformed(evt);
            }
        });

        btnClose.setText(bundle.getString("ListaEmpleados.btnClose.text")); // NOI18N
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrlEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, 668, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnGetBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClose)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGetBack)
                    .addComponent(btnClose))
                .addGap(18, 18, 18)
                .addComponent(scrlEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGetBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetBackActionPerformed
        dispose();
    }//GEN-LAST:event_btnGetBackActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnGetBack;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JScrollPane scrlEmployees;
    private javax.swing.JTable tblEmployees;
    // End of variables declaration//GEN-END:variables
}
