/* 
 * Copyright (C) 2019 Ruslan López Carro
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package inventarios.desktop;

import inventarios.desktop.navigation.NavigationHandler;
import inventarios.service.LoginUsersService;
import inventarios.to.LoginUser;
import inventarios.util.FontFactory;
import inventarios.util.Utils;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.GridLayout;
import java.awt.Image;
import java.awt.Rectangle;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ResourceBundle;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.WindowConstants;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.beans.factory.config.ConfigurableBeanFactory;
import org.springframework.context.annotation.Scope;

/**
 * @author EfraJiJim
 */
@Component
@Scope(ConfigurableBeanFactory.SCOPE_SINGLETON)
public class LoginWindow extends JFrame {

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JPasswordField txtPsswd;
    private JTextField txtUser;
    // End of variables declaration//GEN-END:variables

    private LoginUsersService usersService;
    private FontFactory fontFactory;
    private NavigationHandler navigationHandler;

    @Autowired
    public LoginWindow(@Qualifier("loginVisitor") NavigationHandler navigationHandler,LoginUsersService usersService, FontFactory fontFactory) {
        this.usersService = usersService;
        this.navigationHandler = navigationHandler;
        this.fontFactory = fontFactory;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanel backgroundedPanel = new JPanel(){
            @Override
            public void paintComponent(Graphics g) {
                ImageIcon backgroundImageIcon = new ImageIcon(getClass().getResource("/ImgFondos/fondo 1.png"));
                Image backgroundImage = 
                new ImageIcon(
                    backgroundImageIcon.getImage()
                    .getScaledInstance(this.getWidth(), this.getHeight(), Image.SCALE_SMOOTH)
                ).getImage();
                g.drawImage(backgroundImage,0,0,null); // draw the background image
            }
        }
        ;
        JPanel titlePanel = new JPanel();
        JLabel lblTitle = new JLabel();
        JPanel fieldsAndLogoPanel = new JPanel();
        JPanel fieldsPanel = new JPanel();
        JPanel userPanel = new JPanel();
        JLabel lblUser = new JLabel();
        txtUser = new JTextField();
        JPanel psswPanel = new JPanel();
        JLabel lblPassword = new JLabel();
        txtPsswd = new JPasswordField();
        JLabel lblCorporativeIcon = new JLabel();
        JPanel btnPanel = new JPanel();
        JButton btnAccept = new JButton();
        JButton btnClean = new JButton();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        ResourceBundle bundle = ResourceBundle.getBundle("inventarios/gui/desktop/Bundle"); // NOI18N
        setTitle(bundle.getString("LoginWindow.title")); // NOI18N
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        setIconImage(new ImageIcon(getClass().getResource
            ("/ImgFondos/Icono.png")).getImage());
    setMaximizedBounds(new Rectangle(0, 0, 0, 0));
    setMinimumSize(new Dimension(500, 400));
    addWindowListener(new WindowAdapter() {
        public void windowClosing(WindowEvent evt) {
            windowCloseHandler(evt);
        }
    });

    backgroundedPanel.setOpaque(false);
    backgroundedPanel.setLayout(new BorderLayout());

    titlePanel.setOpaque(false);

    lblTitle.setFont(new Font("Tempus Sans ITC", 1, 36)); // NOI18N
    lblTitle.setForeground(new Color(204, 0, 0));
    lblTitle.setIcon(new ImageIcon(getClass().getResource("/ImgLetras/login.png"))); // NOI18N
    titlePanel.add(lblTitle);

    backgroundedPanel.add(titlePanel, BorderLayout.PAGE_START);

    fieldsAndLogoPanel.setOpaque(false);

    fieldsPanel.setOpaque(false);
    fieldsPanel.setLayout(new GridLayout(2, 2, 20, 15));

    userPanel.setOpaque(false);
    userPanel.setLayout(new GridLayout(1, 0, 5, 0));

    lblUser.setFont(fontFactory.getFont("Montserrat-Light.ttf"));
    lblUser.setForeground(new Color(0, 0, 153));
    lblUser.setText(bundle.getString("LoginWindow.lblUser.text")); // NOI18N
    userPanel.add(lblUser);

    txtUser.addKeyListener(new KeyAdapter() {
        public void keyTyped(KeyEvent evt) {
            txtUserKeyTyped(evt);
        }
    });
    userPanel.add(txtUser);

    fieldsPanel.add(userPanel);

    psswPanel.setOpaque(false);
    psswPanel.setLayout(new GridLayout(1, 0, 5, 0));

    lblPassword.setFont(lblUser.getFont());
    lblPassword.setForeground(new Color(0, 0, 153));
    lblPassword.setText(bundle.getString("LoginWindow.lblPassword.text")); // NOI18N
    psswPanel.add(lblPassword);

    txtPsswd.addKeyListener(new KeyAdapter() {
        public void keyTyped(KeyEvent evt) {
            txtPsswdKeyTyped(evt);
        }
    });
    psswPanel.add(txtPsswd);

    fieldsPanel.add(psswPanel);

    fieldsAndLogoPanel.add(fieldsPanel);

    lblCorporativeIcon.setIcon(new ImageIcon(getClass().getResource("/ImgFondos/Imagen2.png"))); // NOI18N
    fieldsAndLogoPanel.add(lblCorporativeIcon);

    backgroundedPanel.add(fieldsAndLogoPanel, BorderLayout.CENTER);

    btnPanel.setOpaque(false);

    btnAccept.setIcon(new ImageIcon(getClass().getResource("/ImgLetras/aceptar.png"))); // NOI18N
    btnAccept.setBorder(null);
    btnAccept.setContentAreaFilled(false);
    btnAccept.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    btnAccept.addActionListener(new ActionListener() {
        public void actionPerformed(ActionEvent evt) {
            btnAcceptActionPerformed(evt);
        }
    });
    btnPanel.add(btnAccept);

    btnClean.setIcon(new ImageIcon(getClass().getResource("/ImgLetras/limpiar.png"))); // NOI18N
    btnClean.setBorder(null);
    btnClean.setContentAreaFilled(false);
    btnClean.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    btnClean.addActionListener(new ActionListener() {
        public void actionPerformed(ActionEvent evt) {
            btnCleanActionPerformed(evt);
        }
    });
    btnPanel.add(btnClean);

    backgroundedPanel.add(btnPanel, BorderLayout.PAGE_END);

    getContentPane().add(backgroundedPanel, BorderLayout.CENTER);

    pack();
    setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAcceptActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnAcceptActionPerformed
        loginAttempt();
    }//GEN-LAST:event_btnAcceptActionPerformed

    private void btnCleanActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnCleanActionPerformed
        clearFields();
    }//GEN-LAST:event_btnCleanActionPerformed

    private void txtUserKeyTyped(KeyEvent evt) {//GEN-FIRST:event_txtUserKeyTyped
        char cTeclaPresionada = evt.getKeyChar();
        if (cTeclaPresionada == KeyEvent.VK_ENTER) {
            loginAttempt();
        }
    }//GEN-LAST:event_txtUserKeyTyped

    private void txtPsswdKeyTyped(KeyEvent evt) {//GEN-FIRST:event_txtPsswdKeyTyped
        char cTeclaPresionada = evt.getKeyChar();
        if (cTeclaPresionada == KeyEvent.VK_ENTER) {
            loginAttempt();
        }
    }//GEN-LAST:event_txtPsswdKeyTyped

    private void windowCloseHandler(WindowEvent evt) {//GEN-FIRST:event_windowCloseHandler
        Utils.confirmExit();
    }//GEN-LAST:event_windowCloseHandler

    private void loginAttempt() {
        String user = txtUser.getText();
        String password = txtPsswd.getText();

        LoginUser loginUser = new LoginUser(user, password);

        if (usersService.authenticate(loginUser)) {
            navigationHandler.goToMenu(this);
            clearFields();
            return;
        }

        JOptionPane.showMessageDialog(null, "Usuario " + user + " no encontrado", "Credenciales incorrectas", JOptionPane.WARNING_MESSAGE);
    }

    private void clearFields() {
        txtUser.setText("");
        txtPsswd.setText("");
    }

}
