/* 
 * Copyright (C) 2019 Ruslan López Carro
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package inventarios.desktop;

import inventarios.desktop.navigation.NavigationHandler;
import inventarios.service.LoginUsersService;
import inventarios.to.LoginUser;
import inventarios.util.FontFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import javax.swing.*;
import java.awt.*;
import java.awt.event.KeyEvent;
import org.springframework.beans.factory.annotation.Qualifier;

/**
 * @author EfraJiJim
 */
@Component
public class LoginWindow extends javax.swing.JFrame {

    private LoginUsersService usersService;
    private FontFactory fontFactory;
    private NavigationHandler navigationHandler;

    @Autowired
    public LoginWindow(@Qualifier("loginVisitor") NavigationHandler navigationHandler,LoginUsersService usersService, FontFactory fontFactory) {
        this.usersService = usersService;
        this.navigationHandler = navigationHandler;
        this.fontFactory = fontFactory;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundedPanel = new javax.swing.JPanel() {
            @Override
            public void paintComponent(java.awt.Graphics g) {
                javax.swing.ImageIcon backgroundImageIcon = new javax.swing.ImageIcon(getClass().getResource("/ImgFondos/fondo 1.png"));
                Image backgroundImage =
                        new ImageIcon(
                                backgroundImageIcon.getImage()
                                        .getScaledInstance(this.getWidth(), this.getHeight(), Image.SCALE_SMOOTH)
                        ).getImage();
                g.drawImage(backgroundImage, 0, 0, null); // draw the background image
            }
        };
        ;
        titlePanel = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        fieldsAndLogoPanel = new javax.swing.JPanel();
        fieldsPanel = new javax.swing.JPanel();
        userPanel = new javax.swing.JPanel();
        lblUser = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        psswPanel = new javax.swing.JPanel();
        lblPassword = new javax.swing.JLabel();
        txtPsswd = new javax.swing.JPasswordField();
        lblCorporativeIcon = new javax.swing.JLabel();
        btnPanel = new javax.swing.JPanel();
        btnAccept = new javax.swing.JButton();
        btnClean = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("inventarios/gui/desktop/Bundle"); // NOI18N
        setTitle(bundle.getString("LoginWindow.title")); // NOI18N
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImage(new ImageIcon(getClass().getResource
                ("/ImgFondos/Icono.png")).getImage());
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setMinimumSize(new java.awt.Dimension(500, 400));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                windowCloseHandler(evt);
            }
        });

        backgroundedPanel.setOpaque(false);
        backgroundedPanel.setLayout(new java.awt.BorderLayout());

        titlePanel.setOpaque(false);

        lblTitle.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(204, 0, 0));
        lblTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImgLetras/login.png"))); // NOI18N
        titlePanel.add(lblTitle);

        backgroundedPanel.add(titlePanel, java.awt.BorderLayout.PAGE_START);

        fieldsAndLogoPanel.setOpaque(false);

        fieldsPanel.setOpaque(false);
        fieldsPanel.setLayout(new java.awt.GridLayout(2, 2, 20, 15));

        userPanel.setOpaque(false);
        userPanel.setLayout(new java.awt.GridLayout(1, 0));

        lblUser.setFont(fontFactory.getFont("Montserrat-Light.ttf"));
        lblUser.setForeground(new java.awt.Color(0, 0, 153));
        lblUser.setText(bundle.getString("LoginWindow.lblUser.text")); // NOI18N
        userPanel.add(lblUser);

        txtUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUserKeyTyped(evt);
            }
        });
        userPanel.add(txtUser);

        fieldsPanel.add(userPanel);

        psswPanel.setOpaque(false);
        psswPanel.setLayout(new java.awt.GridLayout(1, 0));

        lblPassword.setFont(lblUser.getFont());
        lblPassword.setForeground(new java.awt.Color(0, 0, 153));
        lblPassword.setText(bundle.getString("LoginWindow.lblPassword.text")); // NOI18N
        psswPanel.add(lblPassword);

        txtPsswd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPsswdKeyTyped(evt);
            }
        });
        psswPanel.add(txtPsswd);

        fieldsPanel.add(psswPanel);

        fieldsAndLogoPanel.add(fieldsPanel);

        lblCorporativeIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImgFondos/Imagen2.png"))); // NOI18N
        fieldsAndLogoPanel.add(lblCorporativeIcon);

        backgroundedPanel.add(fieldsAndLogoPanel, java.awt.BorderLayout.CENTER);

        btnPanel.setOpaque(false);

        btnAccept.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImgLetras/aceptar.png"))); // NOI18N
        btnAccept.setBorder(null);
        btnAccept.setContentAreaFilled(false);
        btnAccept.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceptActionPerformed(evt);
            }
        });
        btnPanel.add(btnAccept);

        btnClean.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImgLetras/limpiar.png"))); // NOI18N
        btnClean.setBorder(null);
        btnClean.setContentAreaFilled(false);
        btnClean.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnClean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCleanActionPerformed(evt);
            }
        });
        btnPanel.add(btnClean);

        backgroundedPanel.add(btnPanel, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(backgroundedPanel, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptActionPerformed
        loginAttempt();
    }

    private void PasswordActionPerformed(java.awt.event.ActionEvent evt) {
        loginAttempt();
    }//GEN-LAST:event_btnAcceptActionPerformed

    private void btnCleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCleanActionPerformed
        clearFields();
    }//GEN-LAST:event_btnCleanActionPerformed

    private void txtUserKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserKeyTyped
        char cTeclaPresionada = evt.getKeyChar();
        if (cTeclaPresionada == KeyEvent.VK_ENTER) {
            loginAttempt();
        }
    }//GEN-LAST:event_txtUserKeyTyped

    private void txtPsswdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPsswdKeyTyped
        char cTeclaPresionada = evt.getKeyChar();
        if (cTeclaPresionada == KeyEvent.VK_ENTER) {
            loginAttempt();
        }
    }//GEN-LAST:event_txtPsswdKeyTyped

    private void windowCloseHandler(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_windowCloseHandler
        confirmExit();
    }//GEN-LAST:event_windowCloseHandler

    private void loginAttempt() {
        String user = txtUser.getText();
        String password = txtPsswd.getText();

        LoginUser loginUser = new LoginUser(user, password);

        if (usersService.authenticate(loginUser)) {
            navigationHandler.goToMenu(this);
            this.setVisible(false);
            clearFields();
            return;
        }

        JOptionPane.showMessageDialog(null, "Usuario " + user + " no encontrado", "Credenciales incorrectas", JOptionPane.WARNING_MESSAGE);
    }

    private void clearFields() {
        txtUser.setText("");
        txtPsswd.setText("");
    }

    public void confirmExit() {
        int valor = JOptionPane.showConfirmDialog(this, "¿Está seguro de cerrar la aplicación?", "Advertencia", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (valor == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroundedPanel;
    private javax.swing.JButton btnAccept;
    private javax.swing.JButton btnClean;
    private javax.swing.JPanel btnPanel;
    private javax.swing.JPanel fieldsAndLogoPanel;
    private javax.swing.JPanel fieldsPanel;
    private javax.swing.JLabel lblCorporativeIcon;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUser;
    private javax.swing.JPanel psswPanel;
    private javax.swing.JPanel titlePanel;
    private javax.swing.JPasswordField txtPsswd;
    private javax.swing.JTextField txtUser;
    private javax.swing.JPanel userPanel;
    // End of variables declaration//GEN-END:variables

}
