/*
 * Copyright (C) 2019 Ruslan López <scherzo16 at gmail.com>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package inventarios.desktop;

import com.itextpdf.text.*;
import com.itextpdf.text.pdf.*;

import static inventarios.desktop.newRegistro.lista;
import java.awt.Color;
import java.awt.Cursor;

import java.awt.HeadlessException;
import java.awt.Point;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.LayoutStyle;
import javax.swing.WindowConstants;

/**
 *
 * @author oscar
 */
public class ventana1 extends javax.swing.JFrame {

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton btnDelete;
    private JButton btnNewRecord;
    private JButton btnOpenRecors;
    private JButton btnPrintRecords;
    private JButton btnSearch;
    private JLabel jLabel2;
    private JLabel lblTitle;
    // End of variables declaration//GEN-END:variables

    /**
     * Creates new form ventana1
     */
    public ventana1() {

        initComponents();
    }

    @Override
    public java.awt.Image getIconImage() {
        java.awt.Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("ImagenBloqueo/cheques.png"));

        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new JLabel();
        btnNewRecord = new JButton();
        btnOpenRecors = new JButton();
        btnPrintRecords = new JButton();
        jLabel2 = new JLabel();
        btnDelete = new JButton();
        btnSearch = new JButton();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setTitle("SISTEMAS DE INVENTARIO_ISC.ITSE");
        setIconImage(getIconImage());
        setLocation(new Point(300, 100));
        setResizable(false);

        lblTitle.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblTitle.setForeground(new Color(153, 153, 153));
        lblTitle.setText("SISTEMA DE INVENTARIO");

        btnNewRecord.setIcon(new ImageIcon(getClass().getResource("/incon/ingresar.gif"))); // NOI18N
        btnNewRecord.setText("NUEVO REGISTRO");
        btnNewRecord.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnNewRecord.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btnNewRecordActionPerformed(evt);
            }
        });

        btnOpenRecors.setIcon(new ImageIcon(getClass().getResource("/incon/files_folder_256.png"))); // NOI18N
        btnOpenRecors.setText("VER TODOS LO REGISTROS");
        btnOpenRecors.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnOpenRecors.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btnOpenRecorsActionPerformed(evt);
            }
        });

        btnPrintRecords.setIcon(new ImageIcon(getClass().getResource("/incon/CARSON DELLOSA-9.jpg"))); // NOI18N
        btnPrintRecords.setText("IMPRIMIR TODOS LOS REGISTROS");
        btnPrintRecords.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnPrintRecords.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btnPrintRecordsActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new ImageIcon(getClass().getResource("/incon/sistemas de inventario.jpg"))); // NOI18N
        jLabel2.setCursor(new Cursor(Cursor.HAND_CURSOR));

        btnDelete.setIcon(new ImageIcon(getClass().getResource("/incon/eliminar.gif"))); // NOI18N
        btnDelete.setText("ELIMINAR ARTICULO");
        btnDelete.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnSearch.setIcon(new ImageIcon(getClass().getResource("/ImagenBloqueo/icono_buscar.png"))); // NOI18N
        btnSearch.setText("BUSCAR ARTICULO");
        btnSearch.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnNewRecord, GroupLayout.PREFERRED_SIZE, 207, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(btnOpenRecors)
                        .addGap(18, 18, 18)
                        .addComponent(btnPrintRecords))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(btnSearch)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(btnDelete)
                        .addGap(5, 5, 5)))
                .addContainerGap())
            .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblTitle, GroupLayout.PREFERRED_SIZE, 438, GroupLayout.PREFERRED_SIZE)
                .addGap(162, 162, 162))
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, GroupLayout.PREFERRED_SIZE, 51, GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(btnDelete)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSearch, GroupLayout.PREFERRED_SIZE, 56, GroupLayout.PREFERRED_SIZE)
                        .addGap(113, 113, 113)))
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNewRecord, GroupLayout.PREFERRED_SIZE, 75, GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOpenRecors, GroupLayout.PREFERRED_SIZE, 75, GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPrintRecords))
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewRecordActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnNewRecordActionPerformed
        newRegistro v = new newRegistro();
        v.setVisible(true);
    }//GEN-LAST:event_btnNewRecordActionPerformed

    private void btnOpenRecorsActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnOpenRecorsActionPerformed
        tablaRegistros x = new tablaRegistros();
        x.setVisible(true);
        x.CargarInterfaz();
        RegistroClase c;

        for (int i = 0; i < lista.size(); i++) {
            c = (RegistroClase) lista.get(i);
            x.MostrarDatos(c);
        }


    }//GEN-LAST:event_btnOpenRecorsActionPerformed

    private void btnPrintRecordsActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnPrintRecordsActionPerformed

        JFileChooser LG = new JFileChooser();

        int opcion = LG.showSaveDialog(this);

        if (opcion == JFileChooser.APPROVE_OPTION) {

            File f = LG.getSelectedFile();
            String f1 = f.toString();

            Document documento = new Document();
            FileOutputStream ficheroPdf;

            try {
                ficheroPdf = new FileOutputStream(f1 + ".pdf");
                PdfWriter.getInstance(documento, ficheroPdf);

                documento.open();
                Paragraph parrafo3 = new Paragraph("INSTITUTO TECNOLOGICO SUPERIOR DE ESCARCEGA");
                parrafo3.setAlignment(1);//el 1 es para centrar
                documento.add(parrafo3);
                documento.add(new Paragraph(" "));
                Paragraph parrafo2 = new Paragraph("LISTA DE TODOS LOS ARTICULOS REGISTRADOS");
                parrafo2.setAlignment(1);//el 1 es para centrar
                documento.add(parrafo2);

                documento.add(new Paragraph(" "));
                PdfPTable tabla = new PdfPTable(5);

                tabla.addCell("NOMBRE");
                tabla.addCell("CODIGO");
                tabla.addCell("CATEGORIA");

                tabla.addCell("MODELO");

                tabla.addCell("OBSERVACIONES");

                for (int i = 0; i < lista.size(); i++) {
                    RegistroClase c;
                    c = (RegistroClase) lista.get(i);

                    tabla.addCell(c.getNombre());
                    tabla.addCell(c.getCodigo());
                    tabla.addCell(c.getCategoria());

                    tabla.addCell(c.getModelo());

                    tabla.addCell(c.getObservaciones());

                    // esto nos crea una tabla de 3 Columnas por 2 Filas
                }
                documento.add(tabla);

                Paragraph parrafo5 = new Paragraph("SISTEMAS DE INVENTARIOS");
                parrafo5.setAlignment(1);//el 1 es para centrar
                documento.add(parrafo5);

                documento.close();
                JOptionPane.showMessageDialog(null, "Creacion finalizada");

            } catch (FileNotFoundException | DocumentException | HeadlessException p) {
                JOptionPane.showMessageDialog(null, "ERROR" + p);

            }
        }

    }//GEN-LAST:event_btnPrintRecordsActionPerformed

    private void btnDeleteActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed

        FrameEliminar q = new FrameEliminar();
        q.setVisible(true);


    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnSearchActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:

        AgregarUsuario d = new AgregarUsuario();
        d.setVisible(true);

    }//GEN-LAST:event_btnSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ventana1().setVisible(true);
        });
    }

}
